# -*- Makefile -*-

# Set the name of the project here
PROJECT_NAME := klee
PROJ_VERSION := 0.01

# Set this variable to the top of the LLVM source tree.
LLVM_SRC_ROOT = /home/gfj/work/llvm-2.9

# Set this variable to the top level directory where LLVM was built
# (this is *not* the same as OBJ_ROOT as defined in LLVM's Makefile.config).
LLVM_OBJ_ROOT = /home/gfj/work/llvm-2.9

# Set this to the build mode used to build LLVM (not necessarily the same
# as the build mode used for KLEE)
LLVM_BUILD_MODE = Release+Asserts

# Set the directory root of this project's source files
PROJ_SRC_ROOT := $(subst //,/,/home/gfj/project/src/klee_symbolic_execution)

# Set the root directory of this project's object files
PROJ_OBJ_ROOT := $(subst //,/,/home/gfj/project/src/klee_symbolic_execution)

# Set the root directory of this project's install prefix
PROJ_INSTALL_ROOT := /usr/local

STP_ROOT := /home/gfj/work/stp_install

ENABLE_POSIX_RUNTIME := 1
ENABLE_STPLOG := @ENABLE_STPLOG@
ENABLE_UCLIBC := 1

HAVE_SELINUX := 0

RUNTIME_ENABLE_OPTIMIZED := 1
RUNTIME_DISABLE_ASSERTIONS := 0
RUNTIME_ENABLE_COVERAGE :=
RUNTIME_ENABLE_PROFILING :=

# A list of "features" which tests can check for in XFAIL:
TEST_FEATURE_LIST :=

ifeq ($(HAVE_SELINUX_SELINUX_H),1)
  TEST_FEATURE_LIST += have-selinux
else
  TEST_FEATURE_LIST += no-selinux
endif

CFLAGS := -g -O2
CXXFLAGS := -g -O2
LDFLAGS := 

REQUIRES_RTTI := 0
